"""High-level reporting service for SecureForge."""

from **future** import annotations

from dataclasses import dataclass
from pathlib import Path

from .html import SecurityHTMLReportRenderer
from .models import SecurityReport
from .serializers import SecurityReportSerializer

@dataclass(frozen=True)
class ReportPaths:
"""Paths generated by a SecureForge report operation."""

```
json_path: Path
html_path: Path
```

class SecurityReportService:
"""Generate and persist SecureForge security reports."""

```
def __init__(
    self,
    serializer: SecurityReportSerializer | None = None,
    html_renderer: SecurityHTMLReportRenderer | None = None,
) -> None:
    self.serializer = (
        serializer
        or SecurityReportSerializer()
    )

    self.html_renderer = (
        html_renderer
        or SecurityHTMLReportRenderer()
    )

def generate(
    self,
    report: SecurityReport,
    *,
    json_path: str | Path,
    html_path: str | Path,
) -> ReportPaths:
    """Generate JSON and HTML reports."""
    json_output = self.serializer.write_json(
        report,
        json_path,
    )

    html_output = self.html_renderer.write_html(
        report,
        html_path,
    )

    return ReportPaths(
        json_path=json_output,
        html_path=html_output,
    )
```
